### ISSUE TITLE
Create base class to help creating rules easier

### ISSUE THREAD

**Issue by AdmiringWorm** [gep13/chocolatey-vscode#104]
## Expected Behavior
Creating new rules should be as easy as possible.

## Current Behavior
Currently we need to add all the logic our self, which results in duplication of code.

## Possible Solution
Create a base class with methods to easily create diagnostics, getting nuspec elements, etc.

## Additional
I'm already working on creating this base class.

**Comment by gep13** [comment]
Sounds like a great idea to me!

**Comment by AdmiringWorm** [comment]
@gep13 Anything you want to see in the base class?

Currently I've added methods to create Diagnostics (Requirement, Guidelines, Suggestions and Notes) as well as a single method to get a element by its name.

**Comment by gep13** [comment]
Those sound like the obvious candidates just now, don't need to get "everything" there initially, we can add any others that come up as we are filling out the remaining rules.

**Comment by mkevenaar** [comment]
I was thinking about this myself as well! Thanks for starting this @AdmiringWorm!

**Comment by mkevenaar** [comment]
I think the base class is implemented now, can this issue be closed @AdmiringWorm?

**Comment by AdmiringWorm** [comment]
Yeah, it certainly can. I forgot it wasn't closed, due to the PR not being merged itself.

Not sure what to add as a label for this one though.

/cc @gep13

**Comment by gep13** [comment]
@AdmiringWorm @mkevenaar apologies, this should have been closed.  I have added the `Improvement` label.
