### ISSUE TITLE
Create new package in specified directory

### ISSUE THREAD

**Issue by AdmiringWorm** [gep13/chocolatey-vscode#108]
## Expected Behavior
Would expect the created package to be created in a subdirectory inside the directory that is selected.

## Current Behavior
Currently the package will always be created in a subdirectory in the root of the workspace.

## Possible Solution
Not sure yet.

## Steps to Reproduce (for bugs)

1. Open up a new work space
2. Create a new directory in the workspace
3. Select the directory
4. Run Chocolatey: Create new Chocolatey package
5. See the package will be created in the root workspace

## Context

Makes me always need to move the package directory manually to a different location.

## Your Environment

* Module version used: Latest development build
* Operating System and PowerShell version: Windows 10, Powershell 5.1.17763.316

**Comment by gep13** [comment]
@AdmiringWorm this is as per the initial design.  I had envisioned having a folder structure similar to the AU template, where you would open the `automatic` folder as the workspace, and running the new command, would simply add a new folder with the selected template.

If we can make it so that the selected folder is the target for the new command, that would be pretty cool!

**Comment by AdmiringWorm** [comment]
opening the `automatic` folder kind of defeats the benefit of having certain files in the root of a repository (like, for instance a `.editorconfig` file), as they wouldn't be detected.

So honestly, that would be a noop for me.

I do have a feeling it would be possible to get the selected folder though, although I haven't yet been able to figure out how.

**Comment by AdmiringWorm** [comment]
Found this: https://github.com/Microsoft/vscode/issues/3553

so unfortunately it seems it isn't possible to get the currently selected folder, unless creating a menu for the explorer would be an option.

**Comment by AdmiringWorm** [comment]
If having a context menu for when a user right-click a folder (which would be enough for me), I can look into implementing that.

Thoughts?

/cc @mkevenaar @gep13

**Comment by mkevenaar** [comment]
@AdmiringWorm right click on the folder in vscode? Would work for me too!

I think another option would be:
an extra (first) step to ask for a folder name, by default it's empty
if the name of the folder is entered, check if the folder exists. 
If it does not exists. Ask if the folder should be created.

**Comment by AdmiringWorm** [comment]
That certainly is also an option.

Personally I think I would prefer the ability to right click a folder though (mostly because I hate being prompted for input when it isn't necessary), not that any of them is mutually exclusive.

**Comment by gep13** [comment]
@AdmiringWorm some good points being made here, especially with regard to the top level folder.

I would have no objection to having a right click option on a selected folder.  I would suggest that this is in addition to the `new` command in the command palette.

**Comment by AdmiringWorm** [comment]
@gep13 yeah of course, but I think the command and the menu context could use the same call as well (again, I haven't looked into this yet).

Basically, allowing the command to be passed in an argument, if it's null use the default workspace, if not use the path passed in (if at all possible).

**Comment by gep13** [comment]
@AdmiringWorm yip, that sounds like a good plan!

**Comment by AdmiringWorm** [comment]
@gep13 great. 😄
I will look into it during this weekend then
