### ISSUE TITLE
Use diagnostic IDs for Language Server Packages

### ISSUE THREAD

**Issue by mkevenaar** [gep13/chocolatey-vscode#117]
Relates to #70 

I have found that the `Diagnostic` object can contain a `DiagnosticCode` object. Containing an integer or string value.

Looking at different other vscode packages they use something like [APPLICATION CODE][NUMBER] In our case that would be CHOCO####, so I think we could go down that road.

If we would go with the numbered version I think we should group them a bit.

I would suggest:
CHOCO0### for all Requirements
CHOCO1### for all Guidelines
CHOCO2### for all Suggestions
CHOCO3### for all Notes

Last three digits would be first come, first serve. 

This way we can match these numbers client side and perhaps even use the "lightbulb" to have the user go to the package-validator wiki URL.

/cc: @gep13 @AdmiringWorm @steviecoaster

**Comment by AdmiringWorm** [comment]
Not a bad idea IMO.

**Comment by gep13** [comment]
@mkevenaar this makes sense to me!

My only "concern" is regarding potential for growth.  Do we think that 100 is "enough" for each type?  Should we make it `CHOCO1###`?

**Comment by mkevenaar** [comment]
@gep13 fine by me, let's go with 3 digits. 1000 potential issues per type, ought to be enough for anybody!

**Comment by gep13** [comment]
This is now being implemented.  I have been updating the issue here:

https://github.com/gep13/chocolatey-vscode/issues/70

When the diagnostic code has been assigned to a rule.
