### ISSUE TITLE
Change validation rules to make use of a package class instead of the XmlDocumentSyntax

### ISSUE THREAD

**Issue by AdmiringWorm** [gep13/chocolatey-vscode#137]
## Expected Behavior

When adding a new validation rule, it would be easier if we have a separate class
that is passed in to each validation rule they can use instead of needing to traverse
the xml document syntax itself.

## Current Behavior

Currently, we'll need to traverse the xml document ourself and find the element that we
need to check.

## Possible Solution

Got some ideas I'm testing out, but nothing concrete yet that works.

## Context

The current implementation makes it harder than what is needed to add a validation rule.
As well as isn't really great in regards to performance (when alot of rules gets added).

## Your Environment

* Module version used: 0.8.0 dev build
* Operating System and PowerShell version: Win 10, PS 5.1

I plan to look into this, but also want to gather thoughts of what would be expected.

/cc @mkevenaar @gep13

**Comment by mkevenaar** [comment]
Makes sense to me, the package-validator uses `NuGet.IPackage` to do this.

Perhaps we can make use of that class as well?

**Comment by AdmiringWorm** [comment]
While we could certainly do that, I'm not completely sure we should.

Mainly because we'll need additional information to create a diagnostic in the validation rule.

**Comment by AdmiringWorm** [comment]
And we need that for every property.
