### ISSUE TITLE
Provide a chocolatey package for the extension

### ISSUE THREAD

**Issue by AdmiringWorm** [gep13/chocolatey-vscode#20]
## Expected Behavior
Basically be allowed to do a `choco install chocolatey-vscode` (or something similiar), instead of downloading the vsix manually and running `code --install-extension`. As well as easier to be kept up to date with new releases.

## Current Behavior
No package is provided.

## Possible Solution
Sorry, I don't really believe it's necessary to provide a solution (as you already know how to create a package 😄)

## Context

Sorry, not sure what would be valid to add here.

## Your Environment

* Module version used: 0.4.0.
* Operating System and PowerShell version: Win 10.0.17134.228, POSH: 5.1.17134.228

## Side Note
I'm willing to open a PR to provide the package (as well as integrating it into the build system).

**Comment by gep13** [comment]
@AdmiringWorm I totally hadn’t thought of this! Great idea!

If you are up for submitting a PR for this I would have no objections.

**Comment by AdmiringWorm** [comment]
Sure thing, I'll look into adding one tomorrow

**Comment by gep13** [comment]
@AdmiringWorm sweet!  Let me know if you have any questions.

**Comment by AdmiringWorm** [comment]
seems like it will take a little longer, some stuff came up today so I don't believe I'll be able to create a PR today 😞.

Hopefully tomorrow.

**Comment by gep13** [comment]
@AdmiringWorm not a problem at all, just whenever you have time.

**Comment by gep13** [comment]
I have added the environment variables to AppVeyor, so this should be ready to push on the next release.

**Comment by gep13** [comment]
@AdmiringWorm are you happy to close this issue, and continue any remaining work in separate issues, like GH-28?

**Comment by AdmiringWorm** [comment]
@gep13 sure
