### ISSUE TITLE
Reports that choco is not installed when workspace is not open

### ISSUE THREAD

**Issue by AdmiringWorm** [gep13/chocolatey-vscode#32]
## Expected Behavior
While I really didn't expect it to work, I did expect that the extension
would report the actual reason why it happens. (This is when creating a new package).

## Current Behavior

If no folder/workspace is opened and error is reported with the message
`Chocolatey is not installed.`.

## Possible Solution

Change the message to notify the user that a folder/worskpace needs to be opened,
or disable the commands entirely until one is available.

## Steps to Reproduce (for bugs)

1. Open Visual Studio Code, without opening any folders or workspaces (files can be opened though).
2. Try running any of the available commands that calls the chocolatey executable.
3. Watch and behold!

## Context

Not really affected that much, just noticed this when trying to debug the extension and forgot to open a folder.

## Your Environment

* Module version used: Latest develop source
* Operating System and PowerShell version: Windows 10, Powershell 5.1

**Comment by gep13** [comment]
@AdmiringWorm thanks for catching this!
