### ISSUE TITLE
Ability to pass arguments to choco new command, when values are stored in user/workspace settings

### ISSUE THREAD

**Issue by gep13** [gep13/chocolatey-vscode#38]
VS Code has the ability to house extension related settings in user/workspace settings file.

It would be good to be able to specify some common things in these settings, like maintainer/owner name, etc.  Then, when using these in conjunction with the `choco new` command via the `Create Chocolatey Package(s)` command, automatically pass these values through.

This idea was suggested by @AdmiringWorm

**Comment by AdmiringWorm** [comment]
I would suggest the format of the extension settings to be similiar to the below example:
```json
{
    "chocolatey.new": {
        "maintainer": "Your name please"
    }
}
```

^^ Configuration per command, or the below
```json
{
    "chocolatey": {
        "maintainer": "Your name please"
    }
}
```

^^ Global configuration for the whole extension

**Comment by gep13** [comment]
An example of defining configuration can be found here:

https://github.com/cake-build/cake-vscode/blob/develop/package.json#L101-L297

Which renders the following:

![image](https://user-images.githubusercontent.com/1271146/49331287-8a5a3c80-f592-11e8-97f4-be83be10989a.png)

And then which can be consumed in code here:

https://github.com/cake-build/cake-vscode/blob/develop/src/cakeMain.ts#L27

**Comment by AdmiringWorm** [comment]
Unless I'm missing something, the PR you're linking to is unrelated to this issue.

Looks like you've implemented a way to install templates in that PR, not added the ability to store a maintainer name in the user/workspace settings.

**Comment by gep13** [comment]
>@AdmiringWorm said...
EDIT: NVM, I see now what you meant

😄 

Sorry, I should have made myself clearer.  The ability to install templates brought with it the requirement to also have some configuration which the user can change.  As a result, I went ahead and added this to the package.json file, following the first option which you mentioned above.  I am suggesting that any additional configuration that is added to the extension follow this same way of doing it.

**Comment by gep13** [comment]
And to give an example:

```
  // The Chocolatey Template Packages Configuration
  "chocolatey.templatePackages": {
    "names": [
      "msi.template",
      "zip.template"
    ],
    "source": "https://chocolatey.org/api/v2/"
  }
```

The above is the new default configuration which is contributed by the extension around installing templates onto the current machine.

**Comment by AdmiringWorm** [comment]
I'm looking into implementing this now, and I'm thinking of instead of restricting the allowed properties that the user can set I would like to implement it in a way that users can set pretty much anything they want.

**Comment by gep13** [comment]
More information on what properties can be passed in is documented here:

https://chocolatey.org/docs/commands-new

**Comment by AdmiringWorm** [comment]
I'm aware, I was just using 'maintainerName' as a test (actually also tested with a property not listed there, but in a custom template, which also replaced the value)

**Comment by gep13** [comment]
Oh yeah, absolutely.  Sorry, the above was more for a reminder for me.  When it comes to writing some documentation around this feature, I will likely point people to the above, and explain that they can create their own templates with their own variables.
