### ISSUE TITLE
New Command: Pack

### ISSUE THREAD

**Issue by michaeltlombardi** [gep13/chocolatey-vscode#9]
It would be very useful to be able to run `choco pack` via the command palette in VSCode, so I could stay in one context for my package development.

## Expected Behavior
```
AS A chocolatey package author
WHEN I need to build a chocolatey package
THEN I can do so from the VSCode command pallette
AND I can have some default options available
AND I can pass additional options either manually or via config
```

## Current Behavior

I have to run `choco pack` from the command line somewhere.

## Possible Solution
Implement as a command palette option.

## Context
Now that there's a command for creating new package scaffolding, it would be useful to have a way to run the pack  command as well, unifying the workflow a bit.

Some of the prep work for this may be useful for a debug workflow in the future.

**Comment by gep13** [comment]
@michaeltlombardi couple questions about this, as I actually thought about this command as well....

* Would the extension search for all `nuspec` files in the current workspace?  Or would it expect that there is only one?
* Should the `nuspec` file location be passed in relative to the current workspace root, or should navigation to the same folder of the nuspec occur prior to running `choco pack`.  The reason for this question is that depending on what is done, will affect any files referenced in the nuspec metadata.

**Comment by gep13** [comment]
@michaeltlombardi perhaps the extension should search the current workspace for nuspec files, and then allow the user to select which one to pack?

**Comment by gep13** [comment]
@michaeltlombardi so, I had a quick play last night...

What do you think of the following as a quick prototype?

![2018-09-11_10-07-22](https://user-images.githubusercontent.com/1271146/45349934-92659a00-b5aa-11e8-9204-f27b013d401a.gif)

If you were to open something like this repo:

https://github.com/chocolatey/chocolatey-coreteampackages

Then the ability to support lots of nuspec files in the same workspace would make a lot of sense.

**Comment by michaeltlombardi** [comment]
This is an _awesome_ first pass! This is even better than what I'd envisioned for a first implementation, love that it picks up the files in the workspace.

👍

**Comment by gep13** [comment]
@michaeltlombardi sweet!  I have a little bit of tidy up work to do on it, but I will ship a version, hopefully, this weekend, and you can check it out.

What's next? 😄
