### ISSUE TITLE
Add Feature -- 'Chocolatey: Add API key'

### ISSUE THREAD

**Issue by steviecoaster** [gep13/chocolatey-vscode#94]
From a "Getting Started" Perspective, it would be nice to add in the functionality of `choco apikey` to the Extension. This enables folks who are going to use VSCode exclusively to develop their packages a mechanism to never have to leave the environment, especially when working through creating a package for the first time. 

Yes, the Integrated Terminal is there and can be used, however, I think having the ability from within the extension is beneficial

Process:

`ctrl+Shift+P` and type 'Chocolatey:Add API Key'

This then prompts for:

1. The API key to be used (Helper text linking to https://chocolatey.org/account?), which is passed to the `-k` param of `choco apikey`
2. The source to use (default to https://push.chocolatey.org?), which is passed to the `-s` param of `choco apikey`

**Comment by gep13** [comment]
@steviecoaster this seems like a great idea to me! 👍

**Comment by gep13** [comment]
@steviecoaster are you wanting to take a stab at this?  If so, I can assign it to you.

**Comment by steviecoaster** [comment]
Go ahead. I've already created a branch locally to add this. Typescript makes my brain hurt. Trying to decipher the other commands and see if I can reverse engineer it into making sense and then get it working :)
